sudo: required
services:
  - docker

before_install:
  - docker build -t sanu0602/docker-react -f Dockerfile.dev .

script:
#  - docker run sanu0602/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-704583926758"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key:
    secure: "$aws_secret_key"